"""add_task_runs_and_schedules

Revision ID: 59285897d3d2
Revises: c1d2e3f4a5b6
Create Date: 2026-03-30 13:10:41.374792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59285897d3d2'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_domain_id'), table_name='agents')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=False)
    op.create_index(op.f('ix_agents_domain_id'), 'agents', ['domain_id'], unique=False)
    # ### end Alembic commands ###
